Adding Test Cases for all Models as well as Profiles and Post Controllers
shujaamarwat24/Instagram_Clone pull request #14
Opened 2022-10-28 10:16 UTC by shujaamarwat24

* comment_spec.rb: Added and improved the tests for comment model
* followship_spec.rb: Added and improved the tests for followship model
* like_spec.rb: Added and improved the tests for Like model
* story_spec.rb: Added and improved the tests for story model
* user_spec.rb: Added tests for followship and user association 
* profiles_controller.rb: Made changes to reject_request method
* post_policy: Added changes to post policy
* story_policy: Added changes to story policy
* user_policy.rb: Added changes to reject_request method policy
* rails_helper.rb: Added config option for requests in devise
* posts_spec: Added tests for post controller
* profiles_spec: Added tests for profiles controller

2022-10-28 10:32 UTC, MuhammadMusfir requested changes

2022-10-28 10:32 UTC, MuhammadMusfir commented on app/controllers/profiles_controller.rb
> +        @pending.update(status: 'Accepted')
Missing failure handling for @pending.update

2022-10-28 10:32 UTC, MuhammadMusfir commented on app/controllers/profiles_controller.rb
> +      @pending.update(status: 'Accepted')
Missing failure handling for @pending.update

2022-10-28 10:32 UTC, MuhammadMusfir commented on spec/controllers/posts_spec.rb
> +        expect(flash[:alert]).to eq('You need to sign in or sign up before continuing.')
We don't check/match flash messages usually.

2022-10-31 04:53 UTC, MuhammadMusfir approved these changes

2022-10-31 04:53 UTC, MuhammadMusfir commented on spec/models/post_spec.rb
> +    let(:user1) do
user1 is a bad variable name.

2022-10-31 06:12 UTC, shujaamarwat24 commented on app/controllers/profiles_controller.rb
> +        @pending.update(status: 'Accepted')
Incorporated

2022-10-31 06:12 UTC, shujaamarwat24 commented on app/controllers/profiles_controller.rb
> +      @pending.update(status: 'Accepted')
Incorporated

2022-10-31 06:13 UTC, shujaamarwat24 commented on spec/controllers/posts_spec.rb
> +        expect(flash[:alert]).to eq('You need to sign in or sign up before continuing.')
The problem is that simplecov checks the flash messages and checks to add these to the covered lines

2022-10-31 06:21 UTC, merged